import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import styles from '../../styles/Home.module.css';
import{useDispatch, useSelector} from 'react-redux';
import {getUser} from '../../redux/orders'

export default function Home() {
    const dispatch= useDispatch();
    useEffect(()=>{
        dispatch(getUser());
    },[dispatch]);
    
    const orders= useSelector((state)=>state.orders);
    console.log(orders)
    return (
        <div className={styles.container}>
            <Head>
                <title>orders App hello</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                   Orders Page
                </h1>
            </main>
        </div>
    )
}
